# This GitHub action will check that the developer tools are run
# This checks code quality
# act --secret-file act.env --container-architecture linux/amd64 --workflows .github/workflows/analyze.yaml
name: analyze
on:
  push:
permissions:
  contents: read
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run lint
        run: npm run lint
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run mocha with coverage
        run: npm run test:mocha
