# This GitHub action will publish a package
# act --secret-file act.env --container-architecture linux/amd64 --workflows .github/workflows/release.yaml
name: release
on:
  release:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: 'arkavo-org'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
