# This GitHub action will run integration tests
# Integration tests live here (not unit tests)
# act --secret-file act.env --container-architecture linux/amd64 --workflows .github/workflows/test.yaml
name: test
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
  workflow_run:
    workflows: [build]
    types:
      - completed
permissions:
  contents: read
  packages: read
jobs:
  integration-vite:
    name: integration-vite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install Vite
        run: npm install -g create-vite
      - name: Create Vite App
        run: create-vite test-app --template react-ts
      - name: Install Arkavo
        run: |
          export VERSION=$(npm pkg get version | xargs echo)
          cd test-app
          echo "@arkavo-org:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          npm install @arkavo-org/client@$(echo "${VERSION}-${GITHUB_SHA::8}")
      - name: Copy App with client
        run: cp tests/integration-vite-react-ts-App.tsx test-app/src/App.tsx
      - name: Start Vite App
        run: cd test-app && npm run dev &
      - name: Install dependencies
        working-directory: tests/playwright
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: tests/playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: tests/playwright
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/playwright/playwright-report/
          retention-days: 30
